import './scss.scss';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import { theme } from '../../../scss/custom/globalTheme';
import { TsaNavbar } from '@tsa/ui';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider options={{ key: 'css' }}>
          <ThemeProvider theme={theme}>
            <TsaNavbar
              courses={[
                `Product Design UI/UX`,
                `Fullstack Development`,
                `Data Science`,
                `Frontend Engineering`,
                `Cyber Security`,
                `Advance IG Marketing`,
              ]}
              navLinks={['About Us', 'FAQs', 'Contact Us']}
            />
            {children}
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
